#!/bin/bash

# This script runs the python script that performs merging of consecutive segments with progressively decreasing HMM score. Input must be
# an unzipped segments.actual_RPKM.bed file as generated by the bruseq pipeline. Output will be a fused_dec.bed file that matches the naming
# convention of the original segments file (defined in python main func). More information can be found within python script.

#q    require $SAMPLE $ACTIONS_DIR $GB_RAM $VERSION
#q    require $BIN_SIZE $ANNOTATION $OUTDIR

#$    -N  $STEP_NAME\_$SAMPLE
#$    -wd $OUTDIR
#$    -l  vf=$GB_RAM\G

#PBS  -N  $STEP_NAME\_$SAMPLE
#PBS  -d  $OUTDIR
#PBS  -l  mem=$GB_RAM\gb


# run fused_dec python script
echo "merge segments"
conda run -n bruseq5 python $ACTIONS_DIR/readthru/merge_decreasing_segments_$VERSION.py $OUTDIR/$SAMPLE.$ANNOTATION.spikeins_1.bin_$BIN_SIZE.segments.actual_RPKM.bed

